server:
  port: 8080
#  ssl:
#    key-store: 3702162_wechat.coding-jiangzh.com.pfx
#    key-store-password: 49Jk65Pi

template:
  templates:
    - {"templateId":"1","templateFilePath":"E:/IMOOCView/mksz434 - Kafka多维度系统精讲，从入门到熟练掌握/
    课程资料/kafka-study-coding（更多IT资源 微信zhishivip0001）/kafka-study-coding（更多IT资源 微信）
    /src/main/resources/template/template.json","active": true}
    - {"templateId":"2","templateFilePath":"E:/IMOOCView/mksz434 - Kafka多维度系统精讲，从入门到熟练掌握/
                                                课程资料/kafka-study-coding（更多IT资源 微信zhishivip0001）/kafka-study-coding（更多IT资源 微信）
                                                /src/main/resources/template/template.json","active": false}
  template-result-type: 0  # 0-文件获取 1-数据库获取 2-ES
  template-result-file-path: "E:/IMOOCView/mksz434 - Kafka多维度系统精讲，从入门到熟练掌握/
                                  课程资料/kafka-study-coding（更多IT资源 微信zhishivip0001）/kafka-study-coding（更多IT资源 微信）
                                  /src/main/resources/template/templateResult.json"

wechat:
  kafka:
#  kafka:课程资料
    bootstrap_servers: "127.0.0.1:9092"
    acks_config: "all"
    partitioner_class: "com.imooc.jiangzh.kafka.producer.SamplePartition"


logging:
  config: classpath:logback.xml